name: Release
on:
  push:
    branches: [main]
permissions:
  contents: write
  pull-requests: write
  id-token: write
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@5c625bfb5d1ff62eadeeb3772007f7f66fdcf071
        id: release
        with:
          release-type: node
          include-component-in-tag: false
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        if: ${{ steps.release.outputs.release_created }}
      - uses: pnpm/setup@fbda4c85fc2e1e08721cd8763afea8f48d60f024
        if: ${{ steps.release.outputs.release_created }}
        with:
          cache: true
          require-lockfile: true
      - run: pnpm build
        if: ${{ steps.release.outputs.release_created }}
      - run: pnpm publish --provenance --access public --no-git-checks
        if: ${{ steps.release.outputs.release_created }}
        env:
          pnpm_config__auth: |
            {
              "https://registry.npmjs.org": {
                "@": {
                  "authToken": ${{ toJSON(secrets.NPM_TOKEN) }}
                }
              }
            }
